#!/usr/bin/perl -w

$bindir = shift @ARGV;
$srcdir = shift @ARGV;

system("sed -i 's/yyerror(char/yyerror(const char/' $bindir/pddl+.cpp");

open IN, "g++ -E $srcdir/fixyywrap.cpp |";
open OUT, "> $bindir/fixyywrap.h";

print OUT "#ifndef FIXYYWRAP_H\n";
print OUT "#define FIXYYWRAP_H\n";

while (<IN>) {

	if (m/int yywrap/) {
		print OUT "int yyFlexLexer::yywrap() { return 1; };\n";
	}

}

print OUT "#endif\n";

close IN;
close OUT;

open IN, "< $bindir/pddl+.cpp";
my $has_include = 0;
while (<IN>) {
	if (m/#include "fixyywrap.h"/) {
		$has_include = 1;
		last;
	}
}
close IN;

if (!$has_include) {
	open OUT, ">> $bindir/pddl+.cpp";
	print OUT '#include "fixyywrap.h"';
	print OUT "\n\n";
	close OUT;
}
